Repository HDFGroup/hdf5_plugins, pull requests merged in 2024-08, with the labels that each got.

#125 Add mac dmg binary
  .github/workflows/cmake-ctest.yml
  .github/workflows/release-files.yml
  .github/workflows/remove-files.yml
Labels: enhancement

#126 Add windows code signing
  .github/workflows/cmake-ctest.yml
  .github/workflows/daily-build.yml
Labels: enhancement

#129 Correct dirs for binaries
  .github/workflows/cmake-ctest.yml
Labels: bug

#130 Change osx refs to macos
  .github/workflows/cmake-ctest.yml
  .github/workflows/release-files.yml
  .github/workflows/remove-files.yml
Labels: enhancement

#131 Fix Signing and update VS readme generation
  .github/workflows/cmake-ctest.yml
  BLOSC/config/cmake/HDFMacros.cmake
  BLOSC/config/cmake/binex/config/cmake/HDFMacros.cmake
  BLOSC2/config/cmake/HDFMacros.cmake
  BLOSC2/config/cmake/binex/config/cmake/HDFMacros.cmake
  BSHUF/config/cmake/HDFMacros.cmake
  BSHUF/config/cmake/binex/config/cmake/HDFMacros.cmake
  BZIP2/config/cmake/HDFMacros.cmake
  BZIP2/config/cmake/binex/config/cmake/HDFMacros.cmake
  JPEG/config/cmake/HDFMacros.cmake
  JPEG/config/cmake/binex/config/cmake/HDFMacros.cmake
  LZ4/config/cmake/HDFMacros.cmake
  LZ4/config/cmake/binex/config/cmake/HDFMacros.cmake
  LZF/config/cmake/HDFMacros.cmake
  LZF/config/cmake/binex/config/cmake/HDFMacros.cmake
  MAFISC/config/cmake/HDFMacros.cmake
  MAFISC/config/cmake/binex/config/cmake/HDFMacros.cmake
  SZ/config/cmake/HDFMacros.cmake
  SZ/config/cmake/binex/config/cmake/HDFMacros.cmake
  ZFP/config/cmake/HDFMacros.cmake
  ZFP/config/cmake/binex/config/cmake/HDFMacros.cmake
  ZSTD/config/cmake/HDFMacros.cmake
  ZSTD/config/cmake/binex/config/cmake/HDFMacros.cmake
  config/cmake/HDFMacros.cmake
  config/cmake/binex/config/cmake/HDFMacros.cmake
Labels: bug

#136 Update CODEOWNERS - HDFG devs, Elena, Quincey
  .github/CODEOWNERS
Labels: Component - Misc, Type - Task, Priority - 2. Medium ⏹

#137 update build for deb, rpm, dmg and update CMake code
  CMakeLists.txt
  CMakePresets.json
  community/CMakeLists.txt
  config/cmake-presets/hidden-presets.json
  config/cmake/HDFPluginMacros.cmake
  config/cmake/cacheinit.cmake
  docs/INSTALL_With_CMake.txt
Labels: Component - Build, Component - Misc, Type - Bug, Type - Improvement, Priority - 0. Blocker ⛔

#138 add secrets to release workflow
  .github/workflows/release.yml
Labels: Component - Misc, Type - Task, Priority - 0. Blocker ⛔
